<div id="dlModal" class="modal fade hide">
            
    <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        <h3>Download Directory Lister <small>v2.0.4</small></h3>
    </div>
    
    <div class="modal-body">
        <center>
            <a href="#" class="btn btn-info btn-large"><i class="icon-download-alt"></i> Download zip</a>
            &nbsp;&nbsp;
            <a href="#" class="btn btn-info btn-large"><i class="icon-download-alt"></i> Download tar.gz</a>
            
            <br/><br/>
            
            <p><small class="muted"><strong>NOTE:</strong> Directory Lister requires PHP 5.3 and has been tested with Apache and Nginx.</small></p>
        </center>
        
        <hr/>
        
        <p>Tag list here...</p>
        
    </div>

</div>