<div id="dl-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4>Download Directory Lister <small>v<?php echo $tag; ?></small></h4>
            </div>

            <div class="modal-body">

                <div class="text-center">

                    <a href="<?php echo $dlZip; ?>" class="download-zip btn btn-info btn-lg" target="_blank" onclick="_gaq.push(['_trackEvent', 'File', 'Download', this.href]);">
                        <i class="fa fa-download"></i> Download zip
                    </a>

                    <a href="<?php echo $dlTar; ?>" class="download-tar-gz btn btn-info btn-lg" target="_blank" onclick="_gaq.push(['_trackEvent', 'File', 'Download', this.href]);">
                        <i class="fa fa-download"></i> Download tar.gz
                    </a>

                    <br/><br/>

                    <p class="muted"><i class="fa fa-info-circle"></i> <small>Directory Lister requires PHP 5.3+ and has been tested on Apache and Nginx.</small></p>

                </div>

                <hr/>

                <table class="download-releases table table-hover">

                    <thead>
                        <tr>
                            <th class="col-release-header"><i class="fa fa-flag"></i> Release</th>
                            <th class="hidden-xs">&nbsp;</th>
                            <th class="col-tag-header hidden-xs"><i class="fa fa-tag"></i> Tag</th>
                            <th class="col-download-header" colspan="2"><i class="fa fa-download"></i> Download</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php foreach ($this->releases as $release): ?>
                            <tr>
                                <td class="col-release-name">
                                    <a href="<?php echo $release->url; ?>">
                                        <?php echo $release->name; ?>
                                    </a>
                                </td>
                                <td class="col-spacer hidden-xs">&nbsp;</td>
                                <td class="col-tag hidden-xs">
                                    <a href="https://github.com/DirectoryLister/DirectoryLister/tree/<?php echo $release->tag_name; ?>">
                                        <?php echo $release->tag_name; ?>
                                    </a>
                                </td>
                                <td class="col-zibball">
                                    <a href="<?php echo $release->zipball_url; ?>" target="_blank" onclick="_gaq.push(['_trackEvent', 'File', 'Download', this.href]);">
                                        zip
                                    </a>
                                </td>
                                <td class="col-tarball">
                                    <a href="<?php echo $release->tarball_url; ?>" target="_blank" onclick="_gaq.push(['_trackEvent', 'File', 'Download', this.href]);">
                                        tar.gz
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>

                </table>

                <a href="https://github.com/DirectoryLister/DirectoryLister/releases" class="btn btn-default btn-block">
                    See all Releases
                </a>

            </div>

        </div>
    </div>
</div>