<div id="share-modal" class="modal fade hide">
            
    <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        <h3>Share Directory Lister</h3>
    </div>
    
    <div class="modal-body">
        
        <center>
            <p class="muted">Promote Directory Lister through your favorite social networks!</p>
        </center>
        
        <hr/>
        
        <table id="share-buttons">
            <tbody>
                <tr>
                    <td>
                        <!-- Place this tag where you want the +1 button to render. -->
                        <div class="g-plusone" data-size="medium"></div>
                        
                        <!-- Place this tag after the last +1 button tag. -->
                        <script type="text/javascript">
                          (function() {
                            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                            po.src = 'https://apis.google.com/js/plusone.js';
                            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                          })();
                        </script>
                    </td>
                    
                    <td>
                        <div id="fb-root"></div>
                        <script>(function(d, s, id) {
                          var js, fjs = d.getElementsByTagName(s)[0];
                          if (d.getElementById(id)) return;
                          js = d.createElement(s); js.id = id;
                          js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
                          fjs.parentNode.insertBefore(js, fjs);
                        }(document, 'script', 'facebook-jssdk'));</script>
                        <div class="fb-like" data-send="false" data-layout="button_count" data-width="200" data-show-faces="false"></div>
                    </td>
                    
                    <td>
                        <a href="https://twitter.com/share" class="twitter-share-button" data-hashtags="DirectoryLister">Tweet</a>
                        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                    </td>
                    
                </tr>
            </tbody>
        </table>
        
    </div>
    
</div>