<ul id="site-navigation" class="nav nav-tabs nav-stacked">
    <li><a href="#intro">Introduction <i class="icon-angle-right"></i></a></li>
    <li><a href="#install">Installation <i class="icon-angle-right"></i></a></li>
    <li><a href="#troubleshooting">Troubleshooting <i class="icon-angle-right"></i></a></li>
    <li><a href="#faq">F.A.Q. <i class="icon-angle-right"></i></a></li>
    <li><a href="#contact">Contact <i class="icon-angle-right"></i></a></li>
</ul>

<div class="side-box">
    <div class="side-box-inner">
        <h3>Follow Development</h3>
        <p>Follow development or contribute to Directory Lister on <a href="https://github.com/DirectoryLister">GitHub</a>,
        the social coding platform.</p>
        
        <center>
            <iframe src="http://ghbtns.com/github-btn.html?user=DirectoryLister&repo=DirectoryLister&type=watch&count=true"
            allowtransparency="true" frameborder="0" scrolling="0" width="90" height="20"></iframe>
            
            <iframe src="http://ghbtns.com/github-btn.html?user=DirectoryLister&repo=DirectoryLister&type=fork&count=true"
            allowtransparency="true" frameborder="0" scrolling="0" width="90" height="20"></iframe>
        </center>
        
    </div>
</div>

<div class="side-box">
    <div class="side-box-inner">
        <h3>Share Directory Lister</h3>
        <p>Promote Directory Lister through your favorite social networks!</p>
    </div>
</div>