<div class="social-buttons">

    <table class="social-buttons-table">
        <tbody>
            <tr>
                <td>
                    <!-- Place this tag where you want the +1 button to render. -->
                    <div class="g-plusone" data-size="medium"></div>

                    <!-- Place this tag after the last +1 button tag. -->
                    <script type="text/javascript">
                      (function() {
                        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                        po.src = 'https://apis.google.com/js/plusone.js';
                        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                      })();
                    </script>
                </td>

                <td>
                    <div id="fb-root"></div>
                    <script>(function(d, s, id) {
                      var js, fjs = d.getElementsByTagName(s)[0];
                      if (d.getElementById(id)) return;
                      js = d.createElement(s); js.id = id;
                      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
                      fjs.parentNode.insertBefore(js, fjs);
                    }(document, 'script', 'facebook-jssdk'));</script>
                    <div class="fb-like" data-send="false" data-layout="button_count" data-width="200" data-show-faces="false"></div>
                </td>

                <td>
                    <a href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fwww.directorylister.com&media=http%3A%2F%2Fwww.directorylister.com%2Fimg%2Fdirectory-lister-nix.png&description=Directory%20Lister%20is%20a%20simple%20PHP%20based%20script%20created%20to%20let%20you%20list%20the%20contents%20of%20a%20directory%20and%20all%20it's%20sub-directories%20and%20allow%20you%20to%20navigate%20there%20within." class="pin-it-button" count-layout="horizontal"><img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It" /></a>
                    <script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>
                </td>

                <td>
                    <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                </td>
            </tr>
        </tbody>
    </table>

</div>