<?php echo $this->doctype(); ?>
<html lang="en">
    
<head>
    <?php echo $this->headTitle('PHP Directory Lister'); ?>
    
    <link href="/img/favicon.ico" rel="icon">

    <!-- STYLES -->
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/bootstrap.min.css'); ?>
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/font-awesome.min.css'); ?>
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/style.css'); ?>
    <?php echo $this->headLink(); ?>
    
    <!-- SCRIPTS -->
    <?php $this->headScript()->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js'); ?>
    <?php $this->headScript()->appendFile($this->basePath() . '/js/bootstrap.min.js'); ?>
    <?php $this->headScript()->appendFile($this->basePath() . '/js/directorylister.js'); ?>
    <?php echo $this->headScript(); ?>
    
    <!-- META TAGS -->
    <meta charset="utf-8">
</head>

<body data-spy="scroll" data-target="#site-navigation">
    <div id="site-header" class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
            
                <a href="<?php echo $this->url('home'); ?>" id="site-title" class="brand">
                    <i class="icon-folder-open"></i> Directory Lister
                </a>
                
                <div class="pull-right">
                    <span id="social-buttons">
                        <a href="https://github.com/DirectoryLister/DirectoryLister/"><i class="icon-github-alt"></i></a>
                        <a href="https://twitter.com/directorylister"><i class="icon-twitter"></i></a>
                        <a href="https://plus.google.com/communities/112615185904533662084"><i class="icon-google-plus-sign"></i></a>
                    </span>
                
                    <a href="#dlModal" data-toggle="modal" id="download-btn" class="btn btn-info pull-right"><i class="icon-download-alt"></i> Download</a>
                </div>
            
            </div>
        </div>
    </div>
    
    <div id="site-containter" class="container">
        
        <div class="row">
            
            <div id="side-bar" class="span3">
                <div id="side-bar-inner" data-spy="affix">
                
                    <ul id="site-navigation" class="nav nav-pills nav-stacked">
                        <li><a href="#intro">Introduction</a></li>
                        <li><a href="#instal">Installation</a></li>
                        <li><a href="#troubleshooting">Troubleshooting</a></li>
                        <li><a href="#faq">F.A.Q.</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                    
                    <div class="side-box">
                        <div class="side-box-inner">
                            <h3>Follow Development</h3>
                            <p>Follow development or contribute to Directory Lister on <a href="https://github.com/DirectoryLister">GitHub</a>,
                            the social coding platform.</p>
                            
                            <center>
                                <iframe src="http://ghbtns.com/github-btn.html?user=DirectoryLister&repo=DirectoryLister&type=watch&count=true"
                                allowtransparency="true" frameborder="0" scrolling="0" width="90" height="20"></iframe>
                                
                                <iframe src="http://ghbtns.com/github-btn.html?user=DirectoryLister&repo=DirectoryLister&type=fork&count=true"
                                allowtransparency="true" frameborder="0" scrolling="0" width="90" height="20"></iframe>
                            </center>
                            
                        </div>
                    </div>
                    
                    <div class="side-box">
                        <div class="side-box-inner">
                            <h3>Share Directory Lister</h3>
                            <p>Promote Directory Lister through your favorite social networks!</p>
                        </div>
                    </div>
                
                </div>
            </div>

            <div class="span9">
                
                <?php echo $this->content; ?>
                
            </div>
            
        </div>
        
        <div id="site-footer">
            
            <p>Directory Lister is distributed under the terms of the <a href="http://www.opensource.org/licenses/mit-license.php">MIT License</a>.</p>
            <p>Copyright &copy; <?php echo date('Y'); ?> <a href="http://www.chriskankiewicz.com">Chris Kankiewicz</a></p>
            
        </div>
        
        <div id="dlModal" class="modal fade hide">
            
            <div class="modal-header">
                <a class="close" data-dismiss="modal">×</a>
                <h3>Download Directory Lister <small>v2.0.4</small></h3>
            </div>
            
            <div class="modal-body">
                <center>
                    <a href="#" class="btn btn-info btn-large"><i class="icon-download-alt"></i> Download zip</a>
                    &nbsp;&nbsp;
                    <a href="#" class="btn btn-info btn-large"><i class="icon-download-alt"></i> Download tar.gz</a>
                </center>
                
                <hr/>
                
                <p>Tag list here...</p>
                
            </div>
            
        </div>
        
    </div>
    
    <?php echo $this->inlineScript() ?>
    
</body>
</html>
