<?php echo $this->doctype(); ?>
<html lang="en">
    
<head>
    <?php echo $this->headTitle('PHP Directory Lister'); ?>
    
    <link href="/img/favicon.ico" rel="icon">

    <!-- STYLES -->
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/bootstrap.min.css'); ?>
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/font-awesome.min.css'); ?>
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/style.css'); ?>
    <?php echo $this->headLink(); ?>
    
    <!-- SCRIPTS -->
    <?php $this->headScript()->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js'); ?>
    <?php $this->headScript()->appendFile($this->basePath() . '/js/bootstrap.min.js'); ?>
    <?php $this->headScript()->appendFile($this->basePath() . '/js/directorylister.js'); ?>
    <?php echo $this->headScript(); ?>
    
    <!-- META TAGS -->
    <meta charset="utf-8">
</head>

<body data-spy="scroll" data-target="#site-navigation">
    <div id="site-header" class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
            
                <a href="<?php echo $this->url('home'); ?>" id="site-title" class="brand">
                    <i class="icon-folder-open"></i> Directory Lister
                </a>
                
                <div class="pull-right">
                    <span id="social-buttons">
                        <a href="https://github.com/DirectoryLister/DirectoryLister/" rel="tooltip" title="Follow on GitHub" data-placement="bottom"><i class="icon-github-alt"></i></a>
                        <a href="https://twitter.com/directorylister" rel="tooltip" title="Follow on Twitter" data-placement="bottom"><i class="icon-twitter"></i></a>
                        <a href="https://plus.google.com/communities/112615185904533662084" rel="tooltip" title="Follow on Google+" data-placement="bottom"><i class="icon-google-plus-sign"></i></a>
                    </span>
                
                    <a href="#dlModal"id="download-btn" class="btn btn-info pull-right" data-toggle="modal"><i class="icon-download-alt"></i> Download</a>
                </div>
            
            </div>
        </div>
    </div>
    
    <div id="site-containter" class="container">
        
        <div class="row">
            
            <div id="side-bar" class="span3">
                <div id="side-bar-inner" data-spy="affix">
                
                    <?php echo $this->partial('partial/sideBar.phtml'); ?>
                
                </div>
            </div>

            <div class="span9">
                
                <?php echo $this->content; ?>
                
            </div>
            
        </div>
        
        <div id="site-footer">
            
            <p>Directory Lister is distributed under the terms of the <a href="http://www.opensource.org/licenses/mit-license.php">MIT License</a>.</p>
            <p>Copyright &copy; <?php echo date('Y'); ?> <a href="http://www.chriskankiewicz.com">Chris Kankiewicz</a></p>
            
        </div>
        
        <?php echo $this->partial('partial/dlModal.phtml', array('tags' => $this->tags)); ?>
        
    </div>
    
    <?php echo $this->inlineScript() ?>
    
</body>
</html>
