<?php echo $this->doctype(); ?>
<html lang="en">

<?php $children = $this->viewModel()->getCurrent()->getChildren(); $child = $children[0]; ?>

<head>
    <?php echo $this->headTitle('PHP Directory Lister - The Simple Web Directory Lister'); ?>

    <link href="/img/favicon.ico" rel="icon">

    <!-- META -->
    <?php $this->headMeta()->setCharset('utf-8'); ?>
    <?php $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>

    <?php echo $this->headMeta(); ?>

    <!-- STYLES / FONTS -->
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/bootstrap.min.css'); ?>
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/font-awesome.min.css'); ?>
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/style.css'); ?>

    <?php $this->headLink()->appendStylesheet('//fonts.googleapis.com/css?family=Arvo|Open+Sans:300,400,700'); ?>

    <?php echo $this->headLink(); ?>

    <!-- SCRIPTS -->
    <?php $this->headScript()->appendFile('//code.jquery.com/jquery-2.1.0.min.js'); ?>
    <?php $this->headScript()->appendFile($this->basePath() . '/js/bootstrap.min.js'); ?>
    <?php $this->headScript()->appendFile($this->basePath() . '/js/ZeroClipboard.min.js'); ?>
    <?php $this->headScript()->appendFile($this->basePath() . '/js/directorylister.js'); ?>

    <?php echo $this->headScript(); ?>

    <?php /*
    <script type="text/javascript">
        $(document).ready(function() {
            // Stripe checkout button
            $('#donate-button').click(function() {
                var token = function(res) {
                    // Post token to back end for processing
                    $.post('/application/payment/donate-post', { stripeToken: res.id });
                };

                StripeCheckout.open({
                    key:         '<?php echo $child->stripeKey; ?>',
                    amount:      500,
                    name:        'Directory Lister',
                    description: "Cup o' Joe ($5.00)",
                    token:       token
                });

                return false;
            });
        });
    </script>
    */ ?>

</head>

<body>

    <nav id="site-header" class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">

                <div class="navbar-header">

                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a href="<?php echo $this->url('home'); ?>" id="site-title" class="navbar-brand" title="The Simple Web Directory Lister">

                        <span class="title-img">
                            <img src="/img/logo.png" class="img-circle img-responsive">
                        </span>

                        <span class="title-text">
                            <h1>
                                Directory Lister
                                <small>v<?php echo $child->tag; ?></small>
                            </h1>
                        </span>

                    </a>

                </div>

                <div id="nav-collapse" class="collapse navbar-collapse navbar-right">

                    <div class="">
                        <ul class="nav navbar-nav">

                            <li>
                                <a href="#" class="top-button hidden-xs" title="Top of Page" rel="tooltip" data-placement="bottom">
                                    <i class="fa fa-arrow-up"></i>
                                </a>
                            </li>

                            <li>
                                <a href="#intro">Intro</a>
                            </li>

                            <li>
                                <a href="#install">Install</a>
                            </li>

                            <li>
                                <a href="#faq">FAQs</a>
                            </li>

                            <li>
                                <a href="#contact">Contact</a>
                            </li>

                        </ul>
                    </div>

                </div>

            </div>
        </div>
    </nav>

    <?php echo $this->content; ?>

    <div class="container">
        <div id="site-footer">

            <p>Directory Lister is distributed under the terms of the <a href="http://www.opensource.org/licenses/mit-license.php">MIT License</a>.</p>
            <p>Copyright &copy; <?php echo date('Y'); ?> <a href="http://www.chriskankiewicz.com">Chris Kankiewicz</a></p>

        </div>
    </div>

    <?php echo $this->partial('partial/dl-modal.phtml', array('releases' => $child->releases, 'tag' => $child->tag, 'dlZip' => $child->dlZip, 'dlTar' => $child->dlTar)); ?>

    <?php echo $this->partial('partial/google-analytics.phtml'); ?>

    <?php echo $this->inlineScript(); ?>

</body>
</html>
