<div class="hero-unit">
    <h2>The Simple Web Directory Lister</h2>
    <center>
        <a href="#" class="btn btn-large btn-success">View the Demo</a>
    </center>
</div>

<div id="site-content">
    
    <div id="intro" class="content-section">
        <h2>Introduction</h2>
        <p>Directory Lister is a simple PHP based script created to let you list the contents of
        a directory and all it's sub-directories and allow you to navigate there within. Just
        download and install Directory Lister to any web directory and have immediate access to
        all files and sub-directories under that directory.</p>
         
        <p>We have extensively tested Directory Lister with all major browsers (and several
        non-major ones) to ensure the best experience to the maximum number of users. This 
        ensures you and your users, no matter what browser they're using, will have the best
        possible experience when using Directory Lister.</p>
     
    </div>
    
    <div id="install" class="content-section">
        <h2>Installation</h2>
        <p>The process to install Directory Lister is simple:</p>
        
        <ol>
            <li>Download and extract directory lister</li>
            <li>Upload index.php and the resources folder to your server in the folder you want listed</li>
            <li>Upload additional files to the same directory as index.php</li>
            <li>Use your web browser to navigate to the URL for the directory</li>
        </ol>

        <p>That's it! You should now see a listing of the contents of that directory.</p>
    </div>
    
    <div id="troubleshooting" class="content-section">
        <h2>Troubleshooting</h2>
        <p>Content...</p>
    </div>
    
    
    <div id="faq" class="content-section">
        <h2>Frequently Asked Questions</h2>
        <p>Content...</p>
    </div>
    
    
    <div id="contact" class="content-section">
        <h2>Contact Info</h2>
        <p>Content...</p>
    </div>
    
</div>