<div class="jumbotron">
    <div class="container">

        <div class="row">
            <div class="col-md-12">

                <div class="jumbotron-text">

                    <h2>List the contents of any directory in minutes.</h2>

                    <a href="#dl-modal" id="download-btn" class="btn btn-primary btn-lg" data-toggle="modal">
                        <i class="fa fa-download"></i> Download Directory Lister
                    </a>

                </div>

                <img src="/img/screenshot.png" class="screenshot center-block" alt="Directory Lister Screenshot">

            </div>
        </div>

    </div>
    <div class="jubotron-shadow"></div>
</div>

<div id="page-content" class="container">

    <div class="demo-link-wrapper">
        <a href="http://demo.directorylister.com" class="demo-link-button center-block">
            View Demo <i class="fa fa-arrow-right fa-fw"></i>
        </a>
    </div>

    <?php echo $this->partial('partial/social-buttons.phtml'); ?>

    <div class="row">

        <div class="col-md-4">

            <div class="action-item">
                <div class="action-item-inner">

                    <h3>News &amp; Updates</h3>
                    <p>Get up to date info on the progress on your favorite social networks.</p>

                    <a href="https://plus.google.com/communities/112615185904533662084" class="btn btn-default" title="Follow on Google+" rel="tooltip">
                        <i class="fa fa-google-plus fa-fw"></i>
                    </a>

                    &nbsp;&nbsp;

                    <a href="https://twitter.com/directorylister" class="btn btn-default" title="Follow on Twitter" rel="tooltip">
                        <i class="fa fa-twitter fa-lg fa-fw"></i>
                    </a>

                    &nbsp;&nbsp;

                    <a href="https://github.com/DirectoryLister/DirectoryLister" class="btn btn-default" title="Follow on GitHub" rel="tooltip">
                        <i class="fa fa-github fa-lg fa-fw"></i>
                    </a>

                </div>
            </div>

        </div>

        <div class="col-md-4">

            <div class="action-item">
                <div class="action-item-inner">

                    <h3>Donate with Bitcoin</h3>
                    <p>Your donations help keep Directory Lister free.  Show your support, donate today.</p>

                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-bitcoin"></i></span>
                        <input type="text" id="bitcoin-address" class="form-control" value="1JMmiw1SUkoau3TWZuMbGY3SsosEtHRXCh" readonly="readonly"></input>
                        <span id="bitcoin-button" class="input-group-addon" data-clipboard-target="bitcoin-address">
                            <i class="fa fa-clipboard"></i>
                        </span>
                    </div>

                </div>
            </div>

        </div>

        <div class="col-md-4">

            <div class="action-item">
                <div class="action-item-inner">

                    <h3>Contribute Code</h3>
                    <p>Follow development or contribute directly on <a href="https://github.com/DirectoryLister">GitHub</a>,
                    the social coding platform.</p>

                    <a href="https://github.com/DirectoryLister/DirectoryLister/fork" class="btn btn-default" title="Fork on GitHub" rel="tooltip">
                        <i class="fa fa-code-fork fa-lg"></i> Fork on GitHub
                    </a>

                    <a href="https://github.com/DirectoryLister/DirectoryLister/network" class="badge badge-info" title="<?php echo $forks; ?> forks" rel="tooltip">
                        <?php echo $forks; ?>
                    </a>

                </div>
            </div>

        </div>

    </div>


    <div id="intro" class="row content-section">
        <div class="col-md-12">
            <h2>Introduction</h2>

            <p>Directory Lister is a simple PHP based script created to let you list the contents of
            a directory and all it's sub-directories and allow you to navigate there within. Just
            download and install Directory Lister to any web directory and have immediate access to
            all files and sub-directories under that directory.</p>

            <div class="feature-list row">

                <div class="col-md-4">
                    <div class="feature-box">
                        <div class="feature-box-inner">

                            <h3><i class="fa fa-cloud-upload fa-fw"></i> Simple Installation</h3>

                            <p>Our clear and simple installation instructions will help you get up and running with Directory Lister in minutes.</p>

                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="feature-box">
                        <div class="feature-box-inner">

                            <h3><i class="fa fa-list-alt fa-fw"></i> List Any Directory</h3>

                            <p>Upload files to any web-accessible directory and Direcectory Lister will generate listings for you on-the-fly.</p>

                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="feature-box">
                        <div class="feature-box-inner">

                            <h3><i class="fa fa-cogs fa-fw"></i> Customizable</h3>

                            <p>Theme support is built in to fit your uniqe style.  Control your listing with custom sort ordering of files/folders.</p>

                        </div>
                    </div>
                </div>

            </div>

            <div class="alert alert-warning">
                We have extensively tested Directory Lister with all major browsers (and several
                non-major ones) to ensure the best experience for the maximum number of users. This
                ensures you and your users, no matter what browser they're using, will have the best
                possible experience when using Directory Lister.
            </div>

            <?php /*
            <div class="col-md-6 pull-right">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Hidden Files <i class="fa fa-folder-o fa-border pull-right"></i></h3>
                        <p>Don't want to share everything with the world? Easily define hidden files to be excluded from your listings.</p>
                    </div>
                </div>
            </div>
            */ ?>

        </div>
    </div>

    <div class="row">

        <div id="install" class=" content-section col-md-6">
            <h2>Installation</h2>

            <p>The process to install Directory Lister is simple:</p>

            <ol class="installation-instructions">
                <li>Download and extract Directory Lister</li>
                <li>Copy <code>resources/default.config.php</code> to <code>resources/config.php</code></li>
                <li>Upload <code>index.php</code> and the <code>resources</code> folder to the folder you want listed</li>
                <li>Upload additional files to the same directory as index.php</li>
            </ol>

            <p>That's it! You should now see a directory listing when browsing to your directory.</p>
        </div>

        <div id="troubleshooting" class="content-section col-md-6">
            <h2>Troubleshooting</h2>

            <p>If you're having trouble getting Directory Lister working, try the following:</p>

            <ul>
                <li>Ensure you have the latest version of Directory Lister installed. The current
                version available is <code>v<?php echo $name; ?></code></li>

                <li>Verify you have PHP 5.3 or later installed. You can verify your PHP version by
                running: <code>php --version</code></li>
            </ul>

            <p>Additional help is available via our mailing list at
            <a href="mailto:Directory-Lister@GoogleGroups.com">Directory-Lister@GoogleGroups.com</a></p>
        </div>
    </div>

    <div id="faq" class="content-section">
        <h2>Frequently Asked Questions</h2>

        <dl id="faq-list">
            <dt>Can I use Directory Lister in a project I'm working on for a client / company?</dt>
                <dd>Yes, Directory Lister is released under the <a href="http://opensource.org/licenses/MIT">MIT</a> license. The rights granted by this licenses should be sufficient for most purposes.</dd>

            <dt>Where can I get Directory Lister news and updates?</dt>
                <dd>Currently, the best way to get updates is to follow <a href="https://twitter.com/directorylister">@DirectoryLister</a> on Twitter.</dd>
        </dl>
    </div>

    <div id="contact" class="content-section">
        <h2>Contact Info</h2>

        <p>Contact us via our mailling list at <a href="mailto:Directory-Lister@GoogleGroups.com">Directory-Lister@GoogleGroups.com</a>
        or <a href="https://groups.google.com/forum/?fromgroups#!forum/directory-lister">join our Google Group</a> online.</p>

        <p>Follow Directory Lister on Twitter at <a href="https://twitter.com/directorylister">@DirectoryLister</a>
        or follow the developer at <a href="https://twitter.com/PHLAK">@PHLAK</a></p>

        <p>Find a problem or bug with Directory Lister? <a href="https://github.com/DirectoryLister/DirectoryLister/issues">Open an issue</a>
        on GitHub.</p>
    </div>

</div>
